### PR TITLE
Fix a major error in the call to nn_recv()

### PR DESCRIPTION
**Pull request by manderiasian**

### CODE REVIEW

**Comment by shilpa24balaji** [comment]
nn_recv() buffer is best when allocated by the user or client who knows the exact length of the message instead of using max buffer. We are freeing the memory allocated by user using the nn_freemsg()

**Comment by shilpa24balaji** [comment]
As discussed in scrum our assumption of malloc heap space can be shared across socket is wrong

**Comment by manderiasian** [comment]
nn_recv() or any other recv() socket call MUST allocate the buffer, doing otherwise would be a clear error.

**Comment by shilpa24balaji** [comment]
As described here http://nanomsg.org/v0.1/nn_recv.3.html, nn_recv (s, &buf, NN_MSG, 0); means nanomsg allocates the buffer and should be freed nn_freemsg (buf);

**Pull request closed without merging**
