### PR TITLE
spin_thread.c: don't assume pthread_t can be cast to int

### PR DESCRIPTION
**Pull request by armcc**
Fix build issues for 64bit targets.

### CODE REVIEW

**Comment by schmidtw** [comment]
Good catch!  Do you think we should use `unsigned long` or `uintptr_t`?

**Comment by kraj** [comment]
Uintptr_t seems right here however it also means c99 is needed at minimum

**Comment by armcc** [comment]
I guess that depends whether or not you care about building and testing on 64bit Windows. I'm not sure how useful it really is to try to print a pthread_t value here though, so if 64bit Windows support is a priority then removing the pthread_t value entirely may be a cleaner solution (rather than trying to figure out the correct and portable printf format string for uintptr_t values).

**Comment by armcc** [comment]
I suggest merging the current fix as-is. It works fine for non-Windows 64bit targets and doesn't need any special care with c99 etc.

Dealing with the complexity of using uintptr_t can be left to a separate commit (if anyone really feels it's worth it).

**Comment by schmidtw** [comment]
I'm ok with merging & we can change it later when we're ready to jump to c99 entirely.

**Pull request merged**
